### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by bhandaribhumin** [gildaswise/flutter_phone_auth#4]
Error on both devices :

ios device seems : restricted_client

android seems :

ON Debug:

final onError = (exception, stacktrace) { //

exception has below response :

hashCode:1037681746

runtimeType:Type (PlatformException)

code:”sign_in_failed”

message:”com.google.android.gms.common.api.ApiException: 10: “

details:null

— — —

debugger line

final GoogleSignInAuthentication googleAuth = await user.authentication;

user.authentication has below response:

NoSuchMethodError (NoSuchMethodError: The getter ‘authentication’ was called on null. Receiver: null Tried calling: authentication)

— — -

show error snakbar :

Couldn’t log in with your Google account, please try again

i setup everything but login is not going to success :(

**Comment by gildaswise** [comment]
Did you add `google-services.json` to the `android/app folder`, and followed the [iOS Integration Steps](https://pub.dev/packages/google_sign_in#ios-integration)? This seems like it couldn't fully integrate with the Google stuff. If it's not that, please add the full stacktrace here, right after you try to login.

**Comment by bhandaribhumin** [comment]
carefully fallow all steps and it's not showing me enter phone number, open direct to verification code
<img width="1276" alt="Screenshot 2019-05-23 at 8 31 19 PM" src="https://user-images.githubusercontent.com/3336047/58263519-c4fe9e00-7d99-11e9-9262-a874650cd690.png">

**Comment by gildaswise** [comment]
Can you send the full stacktrace of the error, from Debug Console, when it happens?

**Comment by bhandaribhumin** [comment]
iOS log:

```
flutter: [AUTH] Setting _isRefreshing (false) to true
flutter: ReactiveRefreshIndicator: called onRefresh
flutter: [AUTH] Just got user as: null
```
![Image from iOS](https://user-images.githubusercontent.com/3336047/58264137-004d9c80-7d9b-11e9-83f6-f927e9fb875b.png)


<img width="735" alt="Screenshot 2019-05-23 at 8 41 09 PM" src="https://user-images.githubusercontent.com/3336047/58264243-25daa600-7d9b-11e9-91af-292da565aaf6.png">

**Comment by bhandaribhumin** [comment]
<img width="963" alt="Screenshot 2019-05-23 at 8 44 28 PM" src="https://user-images.githubusercontent.com/3336047/58264489-9681c280-7d9b-11e9-8e5a-66ba40ee79ac.png">

**Comment by gildaswise** [comment]
Seems like the API consent has to do with this: https://console.cloud.google.com/apis/credentials/consent

But did you drag `GoogleService-Info.plist` inside Runner so Xcode recognizes the file? Try generating another one in Project Overview -> Settings icon -> Project Settings.

**Comment by bhandaribhumin** [comment]
ANDROID log: 
when i set AuthStatus.SMS_AUTH; didn't ask me for mobile number

```
E/flutter ( 6965): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'linkWithCredential' was called on null.
E/flutter ( 6965): Receiver: null
E/flutter ( 6965): Tried calling: linkWithCredential(Instance of 'AuthCredential')
E/flutter ( 6965): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)
E/flutter ( 6965): #1      _AuthScreenState._linkWithPhoneNumber 
package:pcpl/routes/auth.dart:228
E/flutter ( 6965): <asynchronous suspension>
E/flutter ( 6965): #2      _AuthScreenState._submitSmsCode 
package:pcpl/routes/auth.dart:213
E/flutter ( 6965): <asynchronous suspension>
E/flutter ( 6965): #3      _AuthScreenState._onRefresh 
package:pcpl/routes/auth.dart:503
E/flutter ( 6965): <asynchronous suspension>
E/flutter ( 6965): #4      ReactiveRefreshIndicatorState._show.<anonymous closure> 
package:pcpl/widgets/reactive_refresh_indicator.dart:365
E/flutter ( 6965): #5      _rootRunUnary  (dart:async/zone.dart:1132:38)
E/flutter ( 6965): #6      _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter ( 6965): #7      _FutureListener.handleValue  (dart:async/future_impl.dart:126:18)
E/flutter ( 6965): #8      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:639:45)
E/flutter ( 6965): #9      Future._propagateToListeners  (dart:async/future_impl.dart:668:32)
E/flutter ( 6965): #10     Future._completeWithValue  (dart:async/future_impl.dart:483:5)
E/flutter ( 6965): #11     Future._asyncComplete.<anonymous closure>  (dart:async/future_impl.dart:513:7)
E/flutter ( 6965): #12     _rootRun  (dart:async/zone.dart:1124:13)
E/flutter ( 6965): #13     _CustomZone.run  (dart:async/zone.dart:1021:19)
E/flutter ( 6965): #14     _CustomZone.runGuarded  (dart:async/zone.dart:923:7)
E/flutter ( 6965): #15     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:963:23)
E/flutter ( 6965): #16     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 6965): #17     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)
E/flutter ( 6965):
```
http://recordit.co/w8INc3BEyC

**Comment by gildaswise** [comment]
The way it works is that you need a FirebaseUser so you can link the phone credential with; if you don't have that then it throws `NoSuchMethodError`. If you want to just verify the phone number, call what you need inside `_linkWithPhoneNumber`, instead of linking.

```
Future<void> _linkWithPhoneNumber(AuthCredential credential) async {
    print("Here the code is already verified and you can proceed.")
}
```

**Comment by bhandaribhumin** [comment]
redownload .plist file and re-add with copy file if needed option check while i drag


but error log : 

```
2019-05-23 21:04:39.597667+0530 Runner[12393:2736118]  - <AppMeasurement>[I-ACS036002] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
2019-05-23 21:04:40.038810+0530 Runner[12393:2736039] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2019-05-23 21:04:40.038854+0530 Runner[12393:2736039] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
2019-05-23 21:04:40.039923+0530 Runner[12393:2736039] Configuring the default Firebase app...
2019-05-23 21:04:40.094557+0530 Runner[12393:2736126] 6.0.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
2019-05-23 21:04:40.131691+0530 Runner[12393:2736039] Configured the default Firebase app __FIRAPP_DEFAULT.
2019-05-23 21:04:40.235066+0530 Runner[12393:2736126] 6.0.0 - [Firebase/Core][I-COR000027] The library name (flutter-firebase_core) or version number (0.4.0+1) contain invalid characters. Only alphanumeric, dash, underscore and period characters are allowed.
2019-05-23 21:04:40.235662+0530 Runner[12393:2736126] 6.0.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60000000 started
2019-05-23 21:04:40.235823+0530 Runner[12393:2736126] 6.0.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2019-05-23 21:04:40.252925+0530 Runner[12393:2736136] flutter: Observatory listening on http://127.0.0.1:60292/0gJk2Q2FTB8=/
2019-05-23 21:04:40.965919+0530 Runner[12393:2736126] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x102906d20] get output frames failed, state 8196
2019-05-23 21:04:40.966117+0530 Runner[12393:2736126] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x102906d20] get output frames failed, state 8196
2019-05-23 21:04:40.966320+0530 Runner[12393:2736126] TIC Read Status [1:0x0]: 1:57
2019-05-23 21:04:40.966897+0530 Runner[12393:2736126] TIC Read Status [1:0x0]: 1:57
```




https://console.cloud.google.com/apis/credentials/consent
link show me you must add Application Homepage link!!!!!!

**Comment by gildaswise** [comment]
I'm really not sure on what's happening with your project. Could you try doing it all from start, with a new Firebase project? Also see [my response above](https://github.com/gildaswise/flutter_phone_auth/issues/4#issuecomment-495270123) on how to deal with not using Google authentication.

**Comment by bhandaribhumin** [comment]
where can i add firebaseUser? 
**Update:** 
also phone number is not accept 12 digit number 91 90XXXX99XX i resolve this but [FYI]

**Comment by gildaswise** [comment]
You'll be skipping `firebaseUser`, you'll just use Firebase to send the SMS code to a number and verify it; on _linkWithPhoneNumber you can just set a `Navigator.of(context).push()` to another screen because the code is verified. Be sure to change the AuthStatus to PHONE_AUTH instead of SMS_AUTH.

**Comment by bhandaribhumin** [comment]
@gildaswise  thanks for your extreme level help, now sms is sending but after verify code i got error:

```
#2      _AuthScreenState._submitSmsCode 
package:pcpl/routes/auth.dart:213
<asynchronous suspension>
#3      _AuthScreenState._onRefresh 
package:pcpl/routes/auth.dart:503
<asynchronous suspension>
#4      ReactiveRefreshIndicatorState._show.<anonymous closure> 
package:pcpl/widgets/reactive_refresh_indicator.dart:365
#5      _rootRunUnary  (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue  (dart:async/future_impl.dart:126:18)
#8      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:639:45)
#9      Future._propagateToListeners  (dart:async/future_impl.dart:668:32)
#10     Future._completeWithValue  (dart:async/future_impl.dart:483:5)
#11     Future._asyncComplete.<anonymous closure>  (dart:async/future_impl.dart:513:7)
#12     _rootRun  (dart:async/zone.dart:1124:13)
#13     _CustomZone.run  (dart:async/zone.dart:1021:19)
#14     _CustomZone.runGuarded  (dart:async/zone.dart:923:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:963:23)
#16     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)
```

**Comment by bhandaribhumin** [comment]
i start fresh but still same :(

```
2019-05-23 21:39:49.552286+0530 Runner[12461:2746188]  - <AppMeasurement>[I-ACS036002] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
2019-05-23 21:39:49.865467+0530 Runner[12461:2746098] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2019-05-23 21:39:49.865511+0530 Runner[12461:2746098] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist.
2019-05-23 21:39:49.866457+0530 Runner[12461:2746098] Configuring the default Firebase app...
2019-05-23 21:39:49.891523+0530 Runner[12461:2746195] 6.0.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
2019-05-23 21:39:49.969623+0530 Runner[12461:2746195] 6.0.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60000000 started
2019-05-23 21:39:49.969832+0530 Runner[12461:2746195] 6.0.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2019-05-23 21:39:49.971426+0530 Runner[12461:2746193] 6.0.0 - [Firebase/Analytics][I-ACS023171] App ID has been changed. Resetting App Measurement data
2019-05-23 21:39:50.033398+0530 Runner[12461:2746209] flutter: Observatory listening on http://127.0.0.1:62597/wtJ0kYcSvck=/
2019-05-23 21:39:50.080119+0530 Runner[12461:2746098] Configured the default Firebase app __FIRAPP_DEFAULT.
2019-05-23 21:39:50.090939+0530 Runner[12461:2746194] 6.0.0 - [Firebase/Core][I-COR000027] The library name (flutter-firebase_core) or version number (0.4.0+1) contain invalid characters. Only alphanumeric, dash, underscore and period characters are allowed.
2019-05-23 21:39:50.906213+0530 Runner[12461:2746193] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x102b2f5c0] get output frames failed, state 8196
2019-05-23 21:39:50.906334+0530 Runner[12461:2746193] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C1.1:2][0x102b2f5c0] get output frames failed, state 8196
2019-05-23 21:39:50.908258+0530 Runner[12461:2746193] TIC Read Status [1:0x0]: 1:57
2019-05-23 21:39:50.908667+0530 Runner[12461:2746193] TIC Read Status [1:0x0]: 1:57
2019-05-23 21:40:05.324865+0530 Runner[12461:2746195] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C2.1:2][0x102b3c290] get output frames failed, state 8196
2019-05-23 21:40:05.325318+0530 Runner[12461:2746195] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C2.1:2][0x102b3c290] get output frames failed, state 8196
2019-05-23 21:40:05.326359+0530 Runner[12461:2746195] TIC Read Status [2:0x0]: 1:57
2019-05-23 21:40:05.326436+0530 Runner[12461:2746195] TIC Read Status [2:0x0]: 1:57
2019-05-23 21:40:05.331038+0530 Runner[12461:2746213] 6.0.0 - [Firebase/Analytics][I-ACS023130] Configuration not found. Using default configuration
2019-05-23 21:40:05.591280+0530 Runner[12461:2746195] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C3.1:2][0x102b54010] get output frames failed, state 8196
2019-05-23 21:40:05.592093+0530 Runner[12461:2746195] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C3.1:2][0x102b54010] get output frames failed, state 8196
2019-05-23 21:40:05.593754+0530 Runner[12461:2746195] TIC Read Status [3:0x0]: 1:57
2019-05-23 21:40:05.593822+0530 Runner[12461:2746195] TIC Read Status [3:0x0]: 1:57
2019-05-23 21:44:07.679311+0530 Runner[12461:2746098] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-05-23 21:44:07.680796+0530 Runner[12461:2746098] [MC] Reading from public effective user settings.
2019-05-23 21:44:07.779997+0530 Runner[12461:2746098] Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 20603_PortraitChoco_iPhone-Simple-Pad_Default
2019-05-23 21:44:18.047220+0530 Runner[12461:2746201] flutter: [AUTH] Setting _isRefreshing (false) to true
2019-05-23 21:44:18.260463+0530 Runner[12461:2746201] flutter: ReactiveRefreshIndicator: called onRefresh
2019-05-23 21:44:18.261869+0530 Runner[12461:2746201] flutter: [AUTH] Setting _isRefreshing (true) to false
2019-05-23 21:44:18.265260+0530 Runner[12461:2746201] flutter: [AUTH] Got phone number as: +9190xx3xxxx2
2019-05-23 21:44:18.339046+0530 Runner[12461:2746201] flutter: [AUTH] Returning null from _verifyPhoneNumber
2019-05-23 21:44:18.339143+0530 Runner[12461:2746201] flutter: [AUTH] Returning null from _submitPhoneNumber
2019-05-23 21:44:18.697898+0530 Runner[12461:2747048] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C4.1:2][0x102a9af80] get output frames failed, state 8196
2019-05-23 21:44:18.698041+0530 Runner[12461:2747048] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C4.1:2][0x102a9af80] get output frames failed, state 8196
2019-05-23 21:44:18.698322+0530 Runner[12461:2747048] TIC Read Status [4:0x0]: 1:57
2019-05-23 21:44:18.698339+0530 Runner[12461:2747048] TIC Read Status [4:0x0]: 1:57
2019-05-23 21:44:28.288098+0530 Runner[12461:2747215] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C5.1:2][0x102b7e6d0] get output frames failed, state 8196
2019-05-23 21:44:28.289032+0530 Runner[12461:2747215] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C5.1:2][0x102b7e6d0] get output frames failed, state 8196
2019-05-23 21:44:28.290026+0530 Runner[12461:2747215] TIC Read Status [5:0x0]: 1:57
2019-05-23 21:44:28.290095+0530 Runner[12461:2747215] TIC Read Status [5:0x0]: 1:57
2019-05-23 21:44:28.302218+0530 Runner[12461:2746201] flutter: [AUTH] Verification code sent to number (91) 90331-59952
2019-05-23 21:44:28.302987+0530 Runner[12461:2746201] flutter: [AUTH] Setting _isRefreshing (false) to false
2019-05-23 21:44:28.304595+0530 Runner[12461:2746201] flutter: [AUTH] Changed status to AuthStatus.SMS_AUTH
2019-05-23 21:44:33.137224+0530 Runner[12461:2746098] Can't find keyplane that supports type 4 for keyboard iPhone-PortraitChoco-NumberPad; using 20603_PortraitChoco_iPhone-Simple-Pad_Default
2019-05-23 21:44:35.347946+0530 Runner[12461:2746201] flutter: [AUTH] Setting _isRefreshing (false) to true
2019-05-23 21:44:35.544265+0530 Runner[12461:2746201] flutter: ReactiveRefreshIndicator: called onRefresh
2019-05-23 21:44:35.545462+0530 Runner[12461:2746201] flutter: [AUTH] _linkWithPhoneNumber called
2019-05-23 21:44:35.553008+0530 Runner[12461:2746201] [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'linkWithCredential' was called on null.
Receiver: null
Tried calling: linkWithCredential(Instance of 'AuthCredential')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _AuthScreenState._linkWithPhoneNumber (package:pcpl/routes/auth.dart:228:29)
<asynchronous suspension>
#2      _AuthScreenState._submitSmsCode (package:pcpl/routes/auth.dart:213:15)
<asynchronous suspension>
#3      _AuthScreenState._onRefresh (package:pcpl/routes/auth.dart:503:22)
<asynchronous suspension>
#4      ReactiveRefreshIndicatorState._show.<anonymous closure> (package:pcpl/widgets/reactive_refresh_indicator.dart:365:16)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

```

**Comment by bhandaribhumin** [comment]
i add dependencies in build.dradle

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'com.google.gms:google-services:3.2.1' 
    }
}

**Comment by gildaswise** [comment]
Did [this error](https://github.com/gildaswise/flutter_phone_auth/issues/4#issuecomment-495279514) happen after you transitioned from the screen or did it trigger a SnackBar? Seems like a state issue where it couldn't find the widget to set it refreshing.

The error with `Tried calling: linkWithCredential(Instance of 'AuthCredential')` just means you didn't remove the `firebaseUser` part, because you're not using google_sign_in anymore. Just change `_linkWithPhoneNumber` to whatever you want to do after verifying the phone number with the SMS code; you can verify by just adding a print.
